apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: nexus
  namespace: apisix
spec:
  http:
    - name: root
      match:
        hosts:
          - ops.example.com
        paths:
          - /nexus*
          - /static/*
          - /service/*
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - ^/nexus(/|$)(.*)
              - /$2
        - name: redirect
          enable: true
          config:
            http_to_https: true
      backends:
        - serviceName: nexus
          servicePort: 8081