apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: busybox
          image: 'busybox:1.28.3'
          command:
            - /bin/sh
            - '-c'
            - sleep 100d
          env:
            - name: VERSION
              value: v1  # v2