apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vmstorage
  namespace: victoriametrics
  labels:
    app: vmstorage
spec:
  serviceName: vmstorage
  selector:
    matchLabels:
      app: vmstorage
  replicas: 2
  template:
    metadata:
      labels:
        app: vmstorage
    spec:
      containers:
        - name: vmstorage
          image: 'victoriametrics/vmstorage:v1.121.0-cluster'
          imagePullPolicy: IfNotPresent
          args:
            - '--storageDataPath=/storage'
            - '--retentionPeriod=1'
            - '--envflag.enable=true'
            - '--envflag.prefix=VM_'
            - '--loggerFormat=json'
          ports:
            - containerPort: 8482
              name: http
            - containerPort: 8400
              name: vminsert
            - containerPort: 8401
              name: vmselect
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: /storage
              name: storage
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        storageClassName: nfs-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vmstorage
  namespace: victoriametrics
  labels:
    app: vmstorage
spec:
  clusterIP: None
  selector:
    app: vmstorage
  ports:
    - name: http
      port: 8482
      targetPort: http
    - name: vminsert
      port: 8400
      targetPort: vminsert
    - name: vmselect
      port: 8401
      targetPort: vmselect