apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitor
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.qq.com:465'
      smtp_from: 3535521945@qq.com
      smtp_auth_username: 3535521945@qq.com
      smtp_auth_password: <授权码>
      smtp_hello: qq.com
      smtp_require_tls: false
    inhibit_rules:
      - source_match:
          alertname: node_memory_usage
          severity: critical
        target_match:
          severity: normal
        equal:
          - instance
    route:
      receiver: default
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      # 分组标签
      group_by:
        - alertname
        - cluster
      routes:
        - receiver: email
          group_wait: 10s
          group_by: 
            - instance
          match:
            team: node
    receivers:
      - name: default
        email_configs:
          - to: 15815085647@163.com
            send_resolved: true
      - name: email
        email_configs:
          - to: 15815085647@163.com
            send_resolved: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitor
  labels:
    app: alertmanager
spec:
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
      containers:
        - name: alertmanager
          image: 'prom/alertmanager:v0.27.0'
          imagePullPolicy: IfNotPresent
          args:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
          ports:
            - containerPort: 9093
              name: http
          volumeMounts:
            - mountPath: /etc/alertmanager
              name: config-volume
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
---
kind: Service
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitor
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
    - protocol: TCP
      port: 9093
      targetPort: http