apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: demo
  namespace: efk
spec:
  version: 8.18.3
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: NodePort
  elasticsearchRef:
    name: demo
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m