apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: local-storage
  local:
    path: /data/k8s/gitlab
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
  namespace: devops
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      labels:
        name: gitlab
    spec:
      initContainers:
        - name: change-permissions
          image: 'busybox:1.35.0'
          command:
            - sh
            - '-c'
            - 'chown -R 1000:1000 /home/git/data'
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /home/git/data
      containers:
        - name: gitlab
          image: 'sameersbn/gitlab:17.5.1'
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: GITLAB_TIMEZONE
              value: Beijing
            - name: GITLAB_SECRETS_DB_KEY_BASE
              value: rqwNzXsVmxMtwwVj7m43XTPgfbnx7WfxbknhhM7zhNvd3sqbcLWVtXwpW4fRCdJn
            - name: GITLAB_SECRETS_SECRET_KEY_BASE
              value: rqwNzXsVmxMtwwVj7m43XTPgfbnx7WfxbknhhM7zhNvd3sqbcLWVtXwpW4fRCdJn
            - name: GITLAB_SECRETS_OTP_KEY_BASE
              value: rqwNzXsVmxMtwwVj7m43XTPgfbnx7WfxbknhhM7zhNvd3sqbcLWVtXwpW4fRCdJn
            - name: GITLAB_ROOT_PASSWORD
              value: admin123
            - name: GITLAB_ROOT_EMAIL
              value: 3535521945@qq.com
            - name: GITLAB_HOST
              value: gitlab.k8s.local
            - name: GITLAB_PORT
              value: '80'
            - name: GITLAB_SSH_PORT
              value: '22'
            - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
              value: 'true'
            - name: GITLAB_NOTIFY_PUSHER
              value: 'false'
            - name: GITLAB_BACKUP_SCHEDULE
              value: daily
            - name: GITLAB_BACKUP_TIME
              value: '01:00'
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: gitlab
            - name: DB_PASS
              value: gitlab
            - name: DB_NAME
              value: gitlab_production
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
          ports:
            - containerPort: 80
              name: http
            - containerPort: 22
              name: ssh
          volumeMounts:
            - mountPath: /home/git/data
              name: data
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 180
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitlab-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: devops
  labels:
    name: gitlab
spec:
  type: NodePort
  selector:
    name: gitlab
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 22
      targetPort: ssh