apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  name: bcj-demo
spec:
  completionPolicy:
    type: Always
    ttlSecondsAfterFinished: 30  # 完成执行后30s被删除
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: counter
          image: busybox
          command:
            - /bin/sh
            - '-c'
            - for i in 1 2 3 4 5 6 7 8 9; do echo $i; done