apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: cs-demo
spec:
  replicas: 3
  minReadySeconds: 60  # Ready状态持续60s，才认为是可用的
  scaleStrategy:
    maxUnavailable: 1
  selector:
    matchLabels:
      app: cs
  template:
    metadata:
      labels:
        app: cs
    spec:
      containers:
        - name: nginx
          image: 'nginx:alpine'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80