apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: victoriametrics
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
    scrape_configs:
      - job_name: nodes
        static_configs:
          - targets:
              - '172.16.0.150:9100'
              - '172.16.0.151:9100'
        relabel_configs:
          - source_labels:
              - __address__
            target_label: ip
            regex: '(.+):(.+)'
            replacement: $1
            action: replace