apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
meta:
  name: vmagent-demo
spec:
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  nodeScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  replicaCount: 1
  remoteWrite:
    - url: 'http://vminsert-vmcluster-demo.default.svc.cluster.local:8480/insert/0/promethesu/api/v1/write'