apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wordpress-pdb
  namespace: kube-example
spec:
  maxUnavailable: 1  # 避免同时删除所有副本
  selector:
    matchLabels:
      app: wordpress
      tier: frontend